# yaml-language-server: $schema=https://raw.githubusercontent.com/billw2012/Bannerlord-Twitch/main/BannerlordTwitch/BannerlordTwitch/Bannerlord-Twitch.schema.json
---
# This config contains many commands for easy testing 
Rewards:
  - RewardSpec:
      Title: Adopt a Hero
      Cost: 5000
      IsEnabled: true
    Action: AdoptAHero
    ActionConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      StartingGold: 0
      StartingEquipmentTier: 0
      StartWithHorse: false
      StartWithArmor: false
  - RewardSpec:
      Title: 10k gold
      Cost: 1000
      IsEnabled: true
    Action: AddGoldToHero
    ActionConfig:
      Amount: 10000
  - RewardSpec:
      Title: 100k gold
      Cost: 10000
      IsEnabled: true
    Action: AddGoldToHero
    ActionConfig:
      Amount: 100000
Commands:
  - Name: stats
    Help: Hero stats
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowGeneral: true
      ShowTopSkills: true
      MinSkillToShow: 50
      ShowAttributes: true
  - Name: inv
    Help: Hero equipment
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowEquipment: true
  - Name: adopt
    Help: Adopt a Hero (subs only)
    Handler: AdoptAHero
    HandlerConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      StartingGold: 100000
      StartingEquipmentTier: 0
      # SubscriberOnly: true
  - Name: summon
    Help: Appear near player (5k gold)
    Handler: SummonHero
    HandlerConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: true
      GoldCost: 5000
      WinGold: 5000
      LoseGold: 5000
  - Name: attack
    Help: Attack player (5k gold)
    Handler: SummonHero
    HandlerConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: false
      GoldCost: 5000
      WinGold: 5000
      LoseGold: 5000
  - Name: skill
    Help: "+Skill (5k gold)"
    Handler: SkillXP
    HandlerConfig:
      Auto: true
      AmountLow: 5000
      AmountHigh: 5000
      GoldCost: 5000
  - Name: attr
    Help: "+Attr (10k gold)"
    Handler: AttributePoints
    HandlerConfig:
      Attribute: Random
      AmountLow: 1
      AmountHigh: 1
      GoldCost: 10000
  - Name: focus
    Help: "+Focus (10k gold)"
    Handler: FocusPoints
    HandlerConfig:
      Auto: true
      AmountLow: 1
      AmountHigh: 1
      GoldCost: 10000
  - Name: equip
    Help: Improve Equip (10k gold x Tier)
    Handler: EquipHero
    HandlerConfig:
      AllowCompanionUpgrade: true
      Armor: true
      Melee: true
      Ranged: true
      Horse: true
      Civilian: true
      Upgrade: true
      GoldCost: 10000
      MultiplyCostByCurrentTier: true
  - Name: giantenemy
    Help: Random enemy giant mode
    Handler: CharacterEffect
    HandlerConfig:
      Name: Giant mode
      Target: EnemyTeam
      Duration: 30
      Scale: 1.5
      Properties:
        - Name: ArmorArms
          Add: 40
        - Name: ArmorEncumbrance
          Add: 100
        - Name: ArmorLegs
          Add: 40
        - Name: ArmorTorso
          Add: 40
        - Name: MaxSpeedMultiplier
          Multiply: 0.75
        - Name: SwingSpeedMultiplier
          Multiply: 0.75
  - Name: babyenemy
    Help: Random enemy baby mode
    Handler: CharacterEffect
    HandlerConfig:
      Name: Baby mode
      Target: EnemyTeam
      Duration: 30
      Scale: 0.5
      Properties:
        - Name: ArmorArms
          Multiply: 0.5
        - Name: ArmorEncumbrance
          Multiply: 0.5
        - Name: ArmorHead
          Multiply: 0.5
        - Name: ArmorLegs
          Multiply: 0.5
        - Name: ArmorTorso
          Multiply: 0.5
        - Name: MaxSpeedMultiplier
          Multiply: 2
  - Name: giantplayer
    Help: Player giant mode
    Handler: CharacterEffect
    HandlerConfig:
      Name: Giant mode
      Target: Player
      Duration: 30
      Scale: 1.5
      Properties:
        - Name: ArmorArms
          Add: 40
        - Name: ArmorEncumbrance
          Add: 100
        - Name: ArmorLegs
          Add: 40
        - Name: ArmorTorso
          Add: 40
        - Name: MaxSpeedMultiplier
          Multiply: 0.75
        - Name: SwingSpeedMultiplier
          Multiply: 0.75
  - Name: babyplayer
    Help: Player baby mode
    Handler: CharacterEffect
    HandlerConfig:
      Name: Baby mode
      Target: Player
      Duration: 30
      Scale: 0.5
      Properties:
        - Name: ArmorArms
          Multiply: 0.5
        - Name: ArmorEncumbrance
          Multiply: 0.5
        - Name: ArmorHead
          Multiply: 0.5
        - Name: ArmorLegs
          Multiply: 0.5
        - Name: ArmorTorso
          Multiply: 0.5
        - Name: MaxSpeedMultiplier
          Multiply: 2
  - Name: gianthero
    Help: Player giant mode
    Handler: CharacterEffect
    HandlerConfig:
      Name: Giant mode
      Target: Adopted
      Duration: 30
      Scale: 1.5
      Properties:
        - Name: ArmorArms
          Add: 40
        - Name: ArmorEncumbrance
          Add: 100
        - Name: ArmorLegs
          Add: 40
        - Name: ArmorTorso
          Add: 40
        - Name: MaxSpeedMultiplier
          Multiply: 0.75
        - Name: SwingSpeedMultiplier
          Multiply: 0.75
  - Name: babyhero
    Help: Player baby mode
    Handler: CharacterEffect
    HandlerConfig:
      Name: Baby mode
      Target: Adopted
      Duration: 30
      Scale: 0.5
      Properties:
        - Name: ArmorArms
          Multiply: 0.5
        - Name: ArmorEncumbrance
          Multiply: 0.5
        - Name: ArmorHead
          Multiply: 0.5
        - Name: ArmorLegs
          Multiply: 0.5
        - Name: ArmorTorso
          Multiply: 0.5
        - Name: MaxSpeedMultiplier
          Multiply: 2
  - Name: burn
    Help: Burn player
    Handler: CharacterEffect
    HandlerConfig:
      Name: Burn
      Duration: 15
      DamagePerSecond: 2
      Properties:
        - Name: MaxSpeedMultiplier
          Multiply: 0.5
      ParticleEffects:
        - Name: psys_game_burning_agent
          OnBody: true
  - Name: heal
    Help: Heal player
    Handler: CharacterEffect
    HandlerConfig:
      Name: Heal
      Duration: 15
      HealPerSecond: 3
      ParticleEffects:
        - Name: psys_bug_fly_1
          OnBody: true
  - Name: healhero
    Help: Heal Adopted Hero
    Handler: CharacterEffect
    HandlerConfig:
      Name: Heal
      Duration: 15
      Target: Adopted
      HealPerSecond: 3
      ParticleEffects:
        - Name: psys_bug_fly_1
          OnBody: true          
  - Name: firesword
    Help: Fire Sword
    Handler: CharacterEffect
    HandlerConfig:
      Name: Firesword
      Duration: 30
      Properties:
        - Name: SwingSpeedMultiplier
          Multiply: 2
        - Name: MaxSpeedMultiplier
          Multiply: 1.1
      ParticleEffects:
        - Name: psys_torch_fire_moving
          OnWeapon: true
  - Name: fireswordhero
    Help: Fire Sword for Adopted Hero
    Handler: CharacterEffect
    HandlerConfig:
      Name: Firesword
      Duration: 30
      Target: Adopted
      Properties:
        - Name: SwingSpeedMultiplier
          Multiply: 2
        - Name: MaxSpeedMultiplier
          Multiply: 1.1
      ParticleEffects:
        - Name: psys_torch_fire_moving
          OnWeapon: true
  - Name: fury
    Help: Player Fists of Fury
    Handler: CharacterEffect
    HandlerConfig:
      Name: Fists of Fury
      DamageMultiplier: 10
      Duration: 20
      ActivateParticleEffect: psys_burning_projectile_stone_coll
      ActivateSound: event:/mission/combat/impact/burning_jar/adobe
      DeactivateParticleEffect: psys_burning_projectile_water_coll
      DeactivateSound: event:/mission/siege/merlon/stone_destroy
      Properties:
        - Name: SwingSpeedMultiplier
          Multiply: 3
        - Name: MaxSpeedMultiplier
          Multiply: 2
      ParticleEffects:
        - Name: psys_torch_fire_moving
          OnHands: true
        - Name: psys_game_burning_agent
          OnHands: true
        - Name: psys_campfire
          OnHands: true
        - Name: psys_campfire_sparks
          OnHands: true
        - Name: psys_campfire_sparks
          OnHands: true
        - Name: psys_campfire_sparks
          OnHands: true
      ForceDropWeapons: true
  - Name: dust
    Help: Dust storm
    Handler: CharacterEffect
    HandlerConfig:
      Name: Dust storm
      Duration: 20
      ParticleEffects:
        - Name: psys_adobe_battlement_destroyed
          OnHead: true
  - Name: pfxtest
    Help: Test particle effects on the player
    Handler: TestPfx
    BroadcasterOnly: true
  - Name: sfxtest
    Help: Test sounds effects
    Handler: TestSfx
    BroadcasterOnly: true    
    
GlobalConfigs: []
SimTesting:
  UserCount: 10
  UserStayTime: 300
  IntervalMinMS: 500
  IntervalMaxMS: 2500
  Init:
    - Type: Reward
      Id: Adopt a Hero
  Use:
    - Type: Reward
      Id: 10k gold
    - Type: Reward
      Id: 100k gold
    - Type: Command
      Id: adopt
    - Type: Command
      Id: summon
    - Type: Command
      Id: attack
    - Type: Command
      Id: skill
    - Type: Command
      Id: attr
    - Type: Command
      Id: focus
    - Type: Command
      Id: equip
    - Type: Command
      Id: stats
    - Type: Command
      Id: inv
