# yaml-language-server: $schema=https://raw.githubusercontent.com/billw2012/Bannerlord-Twitch/main/BannerlordTwitch/BannerlordTwitch/Bannerlord-Twitch.schema.json
---
# This config uses bot commands only: subs can adopt a hero for free, with some starting money, then earn more through
# attacking the player and winning, which they can use to upgrade.
Rewards:
  - Cmd: stats
    Help: Hero stats
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowGeneral: true
      ShowTopSkills: true
      MinSkillToShow: 50
      ShowAttributes: true
  - Cmd: inv
    Help: Hero equipment
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowEquipment: true
  - Cmd: adopt
    Help: Adopt a Hero (subs only)
    Handler: AdoptAHero
    HandlerConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      SubscriberOnly: true
      StartingGold: 20000
      StartingEquipmentTier: 0
  - Cmd: adopt2
    Help: Adopt a Better Hero (2 month subs only)
    Handler: AdoptAHero
    HandlerConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      SubscriberOnly: true
      MinSubscribedMonths: 2
      StartingGold: 50000
      StartingEquipmentTier: 2
  - Cmd: summon
    Help: Appear near player (5k gold)
    Handler: SummonHero
    HandlerConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: true
      GoldCost: 5000
  - Cmd: attack
    Help: Attack (+/- 10k gold)
    Handler: SummonHero
    HandlerConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: false
      GoldCost: 0
      WinGold: 10000
  - Cmd: skill
    Help: "+Skill (5k gold)"
    Handler: SkillXP
    HandlerConfig:
      Auto: true
      AmountLow: 5000
      AmountHigh: 5000
      GoldCost: 5000
  - Cmd: attr
    Help: "+Attr (10k gold)"
    Handler: AttributePoints
    HandlerConfig:
      Improvement: Vigor, Control, Endurance, Cunning, Social, Intelligence
      Random: true
      AmountLow: 1
      AmountHigh: 1
      GoldCost: 10000
  - Cmd: focus
    Help: "+Focus (10k gold)"
    Handler: FocusPoints
    HandlerConfig:
      Auto: true
      AmountLow: 1
      AmountHigh: 1
      GoldCost: 10000
  - Cmd: equip
    Help: +Equipment (15k gold)
    Handler: EquipHero
    HandlerConfig:
      AllowCompanionUpgrade: true
      Armor: true
      Melee: true
      Ranged: true
      Horse: true
      Civilian: true
      Upgrade: true
      GoldCost: 15000
