# yaml-language-server: $schema=https://raw.githubusercontent.com/billw2012/Bannerlord-Twitch/main/BannerlordTwitch/BannerlordTwitch/Bannerlord-Twitch.schema.json
---
# This config uses only channel point rewards, and provides simple upgrade mechanics (e.g. random skill etc.)
Rewards:
  - RewardSpec:
      Title: Adopt a Hero
      Cost: 5000
      IsEnabled: true
    Action: AdoptAHero
    ActionConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      StartingGold: 0
      StartingEquipmentTier: 0
      StartWithHorse: false
      StartWithArmor: false
  - RewardSpec:
      Title: Summon Hero
      Cost: 2000
      IsEnabled: true
    Action: SummonHero
    ActionConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: true
  - RewardSpec:
      Title: Attack Player
      Cost: 2000
      IsEnabled: true
    Action: SummonHero
    ActionConfig:
      AllowFriendlyMission: true
      OnPlayerSide: false
      WinGold: 10000
  - RewardSpec:
      Title: +Skills
      Cost: 2000
      IsEnabled: true
    Action: SkillXP
    ActionConfig:
      Auto: true
      AmountLow: 5000
      AmountHigh: 5000
  - RewardSpec:
      Title: +Attributes
      Cost: 5000
      IsEnabled: true
    Action: AttributePoints
    ActionConfig:
      Improvement: Vigor, Control, Endurance, Cunning, Social, Intelligence
      Random: true
      AmountLow: 1
      AmountHigh: 1
  - RewardSpec:
      Title: +Focus
      Cost: 5000
      IsEnabled: true
    Action: FocusPoints
    ActionConfig:
      Auto: true
      AmountLow: 1
      AmountHigh: 1
  - RewardSpec:
      Title: +Equipment
      Cost: 2000
      IsEnabled: true
    Action: EquipHero
    ActionConfig:
      Upgrade: true
      AllowCompanionUpgrade: true
      Armor: true
      Melee: true
      Ranged: true
      Horse: true
      Civilian: true
Commands:
  - Name: stats
    Help: Hero stats
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowGeneral: true
      ShowTopSkills: true
      MinSkillToShow: 50
      ShowAttributes: true
  - Name: inv
    Help: Hero equipment
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowEquipment: true
