# yaml-language-server: $schema=https://raw.githubusercontent.com/billw2012/Bannerlord-Twitch/main/BannerlordTwitch/BannerlordTwitch/Bannerlord-Twitch.schema.json
---
# This config uses bot commands only: subs can adopt a hero for free, with some starting money, then earn more through
# their side winning in battle, which they can use to upgrade equipment and stats.
Rewards:
  - Name: stats
    Help: Hero stats
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowGeneral: true
      ShowTopSkills: true
      MinSkillToShow: 50
      ShowAttributes: true
  - Name: inv
    Help: Hero equipment
    Handler: HeroInfoCommand
    HandlerConfig:
      ShowEquipment: true
  - Name: adopt
    Help: Adopt a Hero (subs only)
    Handler: AdoptAHero
    HandlerConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      SubscriberOnly: true
      StartingGold: 20000
      StartingEquipmentTier: 0
  - Name: adopt2
    Help: Adopt a Better Hero (2 month subs only)
    Handler: AdoptAHero
    HandlerConfig:
      AllowNoble: true
      AllowWanderer: true
      AllowNewAdoptionOnDeath: true
      SubscriberOnly: true
      MinSubscribedMonths: 2
      StartingGold: 50000
      StartingEquipmentTier: 2
  - Name: summon
    Help: Appear near player (5k gold)
    Handler: SummonHero
    HandlerConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: true
      GoldCost: 5000
  - Name: attack
    Help: Attack (+/- 10k gold)
    Handler: SummonHero
    HandlerConfig:
      AllowFieldBattle: true
      AllowSiegeBattle: true
      AllowVillageBattle: true
      AllowArena: true
      AllowHideOut: true
      AllowFriendlyMission: true
      OnPlayerSide: false
      # Free to attack!
      GoldCost: 0 
      WinGold: 10000
  - Name: skill
    Help: "+Skill (5k gold)"
    Handler: SkillXP
    HandlerConfig:
      Auto: true
      AmountLow: 5000
      AmountHigh: 5000
      GoldCost: 5000
  - Name: attr
    Help: "+Attr (10k gold)"
    Handler: AttributePoints
    HandlerConfig:
      Attribute: Random
      AmountLow: 1
      AmountHigh: 1
      GoldCost: 10000
  - Name: focus
    Help: "+Focus (10k gold)"
    Handler: FocusPoints
    HandlerConfig:
      Auto: true
      AmountLow: 1
      AmountHigh: 1
      GoldCost: 10000
  - Name: equip
    Help: "Improve Equip (10k gold x Tier)"
    Handler: EquipHero
    HandlerConfig:
      AllowCompanionUpgrade: true
      Armor: true
      Melee: true
      Ranged: true
      Horse: true
      Civilian: true
      Upgrade: true
      GoldCost: 10000
      MultiplyCostByCurrentTier: true
