import { Check, ChevronDown, Clock3, Copy, Link2, Power, RotateCw, Save, Search, ShieldAlert, SlidersHorizontal, Unplug, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createPairingCode, getConfigurationContext, revokeInstallation, saveConfiguration } from "../api";
import { LanguageSelector } from "../i18n";
import { authorizeViewer } from "../twitch";
import type { ActionManifest, ChannelConfiguration, ConfigurationContext, ManifestAction, PairingDecision, ViewerIdentity } from "../types";
type ConfigMode = "full" | "live";
export function ConfigurationApp({ mode }: { mode: ConfigMode }) {
  const [identity, setIdentity] = useState<ViewerIdentity>(); const [manifest, setManifest] = useState<ActionManifest>(); const [error, setError] = useState<string>();
  useEffect(() => { Promise.all([authorizeViewer(), fetch("./action-manifest.json").then(r => r.json() as Promise<ActionManifest>)]).then(([viewer, actions]) => { setIdentity(viewer); setManifest(actions); }).catch(reason => setError(String(reason))); }, []);
  if (error || !identity || !manifest) return <main className="configuration-view"><div className="config-access" role={error ? "alert" : undefined}>{error ? <ShieldAlert /> : null}{error ?? "Loading configuration…"}</div></main>;
  return <ConfigurationView identity={identity} manifest={manifest} mode={mode} />;
}
export function ConfigurationView({ identity, manifest, mode }: { identity: ViewerIdentity; manifest: ActionManifest; mode: ConfigMode }) {
  const [context, setContext] = useState<ConfigurationContext>(); const [draft, setDraft] = useState<ChannelConfiguration>(); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All");
  const [code, setCode] = useState<string>(); const [expiresAt, setExpiresAt] = useState<string>(); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  const [expandedAction, setExpandedAction] = useState<string>();
  const [pairingDecisions, setPairingDecisions] = useState<Record<string, PairingDecision["decision"]>>({});
  const [now, setNow] = useState(Date.now());
  const [codeCopied, setCodeCopied] = useState(false);
  const broadcaster = identity.roles.includes("broadcaster");
  const load = useCallback(async () => { setError(undefined); try { const result = await getConfigurationContext(identity); setContext(result); setDraft(result.configuration); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }, [identity]);
  useEffect(() => { if (broadcaster) void load(); }, [broadcaster, load]);
  useEffect(() => { if (!broadcaster || mode !== "full") return; const timer = window.setInterval(() => { setNow(Date.now()); void getConfigurationContext(identity).then(result => setContext(current => current ? { ...result, configuration: current.configuration } : result)); }, 2000); return () => window.clearInterval(timer); }, [broadcaster, identity, mode]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const enabled = useMemo(() => new Map(draft?.commands.map(item => [item.actionId, item.enabled]) ?? []), [draft]);
  const preferences = useMemo(() => new Map(draft?.commands.map(item => [item.actionId, item]) ?? []), [draft]);
  const categories = useMemo(() => ["All", ...new Set(manifest.actions.map(action => action.category))], [manifest]);
  const filtered = useMemo(() => manifest.actions.filter(action => (category === "All" || action.category === category) && `${action.legacyName} ${action.description} ${action.handler}`.toLowerCase().includes(query.toLowerCase())), [manifest, category, query]);
  const enabledCount = manifest.actions.filter(action => enabled.get(action.id) ?? action.enabledByDefault).length;
  const configDirty = Boolean(draft && context && JSON.stringify({ activeProfile: draft.activeProfile, extensionEnabled: draft.extensionEnabled, profiles: draft.profiles }) !== JSON.stringify({ activeProfile: context.configuration.activeProfile, extensionEnabled: context.configuration.extensionEnabled, profiles: context.configuration.profiles }));
  const dirty = configDirty || Object.keys(pairingDecisions).length > 0;
  function setCommands(commands: ChannelConfiguration["commands"]) { setDraft(current => current ? { ...current, commands, profiles: current.profiles.map(profile => profile.profileId === current.activeProfile ? { ...profile, commands } : profile) } : current); }
  function setCommand(action: ManifestAction, value: boolean) { setCommands(manifest.actions.map(item => ({ ...preferences.get(item.id), actionId: item.id, enabled: item.id === action.id ? value : (enabled.get(item.id) ?? item.enabledByDefault) }))); }
  function setSetting(action: ManifestAction, settingId: string, value: boolean | number | string) { const current = preferences.get(action.id); setCommands(manifest.actions.map(item => item.id === action.id ? { ...current, actionId: item.id, enabled: current?.enabled ?? item.enabledByDefault, settings: { ...current?.settings, [settingId]: value } } : { ...preferences.get(item.id), actionId: item.id, enabled: enabled.get(item.id) ?? item.enabledByDefault })); }
  function selectProfile(profileId: number) { setDraft(current => { if (!current) return current; const profile = current.profiles.find(item => item.profileId === profileId) ?? { profileId, extensionEnabled: true, commands: [] }; return { ...current, activeProfile: profileId, extensionEnabled: profile.extensionEnabled, commands: profile.commands, profiles: current.profiles.some(item => item.profileId === profileId) ? current.profiles : [...current.profiles, profile] }; }); }
  async function save() { if (!draft) return; setSaving(true); setError(undefined); try { const decisions = Object.entries(pairingDecisions).map(([requestId, decision]) => ({ requestId, decision })); const result = await saveConfiguration(identity, draft, decisions); setDraft(result); setPairingDecisions({}); const refreshed = await getConfigurationContext(identity); setContext(refreshed); setMessage(decisions.length ? "Configuration and pairing decisions saved." : "Configuration saved and sent to connected overlays."); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  async function newCode() { setError(undefined); try { const result = await createPairingCode(identity); setCode(result.code); setExpiresAt(result.expiresAt); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  async function copyCode() { if (!code) return; setCodeCopied(false); setError(undefined); const fallback = () => { const input = document.createElement("textarea"); input.value = code; input.style.position = "fixed"; input.style.opacity = "0"; document.body.appendChild(input); input.select(); const copied = document.execCommand("copy"); input.remove(); return copied; }; try { let copied = false; if (navigator.clipboard?.writeText) { try { await navigator.clipboard.writeText(code); copied = true; } catch { copied = fallback(); } } else copied = fallback(); if (!copied) throw new Error("Copy was rejected."); setCodeCopied(true); window.setTimeout(() => setCodeCopied(false), 1800); } catch { setError("The code could not be copied. Select it and copy it manually."); } }
  async function revoke(id: string) { try { await revokeInstallation(identity, id); await load(); setMessage("Installation revoked."); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  const pendingRequests = context?.pairingRequests.filter(request => request.status === "pending" && new Date(request.expiresAt).getTime() > now) ?? [];
  const secondsLeft = expiresAt ? Math.max(0, Math.ceil((new Date(expiresAt).getTime() - now) / 1000)) : 0;
  if (!broadcaster) return <main className="configuration-view"><div className="config-access" role="alert"><ShieldAlert /><h1>Broadcaster access required</h1><p>This public Twitch asset contains no channel data. Open it from your Extension configuration in the broadcaster dashboard.</p></div></main>;
  if (!draft || !context) return <main className="configuration-view"><div className="config-access">{error ?? "Loading broadcaster configuration…"}</div></main>;
  return <main className={`configuration-view config-${mode}`}>
    <header className="config-header"><div><span className="config-kicker">BLT Twitch Extension</span><h1>{mode === "live" ? "Live controls" : "Streamer configuration"}</h1><p>{identity.displayName} · Channel {identity.channelId}</p></div><LanguageSelector /></header>
    <section className="config-status-row"><div className={context.gameConnected ? "healthy" : "offline"}><span />Game {context.gameConnected ? "connected" : "offline"}</div><div className={context.installations.some(i => !i.revokedAt) ? "healthy" : "offline"}><span />{context.installations.filter(i => !i.revokedAt).length} active installation(s)</div><label className="master-switch"><Power /><span><strong>Extension commands</strong><small>Chat commands and rewards are unaffected</small></span><input type="checkbox" checked={draft.extensionEnabled} onChange={event => setDraft(current => current ? { ...current, extensionEnabled: event.target.checked, profiles: current.profiles.map(profile => profile.profileId === current.activeProfile ? { ...profile, extensionEnabled: event.target.checked } : profile) } : current)} /></label></section>
    <section className="config-presets"><strong>Configuration profile</strong><div>{[1,2,3].map(profileId => <button className={draft.activeProfile === profileId ? "active" : ""} key={profileId} onClick={() => selectProfile(profileId)}>Profile {profileId}</button>)}</div><small>Each profile is saved independently. New profiles begin with BLT defaults.</small></section>
    {mode === "full" ? <><section className="config-setup pairing-workflow"><div className="pairing-guide"><h2><Link2 /> Pair BLT Configure</h2><ol><li><span>1</span><div><strong>Generate a one-time code</strong><p>The code is valid for ten minutes.</p></div></li><li><span>2</span><div><strong>Paste it into BLT Configure</strong><p>Press Pair there. Nothing happens merely by focusing or leaving a field.</p></div></li><li><span>3</span><div><strong>Review the request here</strong><p>Choose Accept or Deny, then press Save below.</p></div></li></ol>{code && secondsLeft > 0 ? <div className="pairing-code"><span>{code}</span><button aria-label={codeCopied ? "Pairing code copied" : "Copy pairing code"} onClick={() => void copyCode()}><Copy /></button>{codeCopied ? <em role="status">Copied</em> : null}</div> : null}<div className="pairing-meta"><span>{code && secondsLeft > 0 ? <><Clock3 /> Expires in {Math.floor(secondsLeft / 60)}:{String(secondsLeft % 60).padStart(2, "0")}</> : "No active pairing code"}</span><button onClick={() => void newCode()}><RotateCw />Generate code</button></div></div><div className="pairing-review"><h2>Pair requests</h2>{pendingRequests.length ? pendingRequests.map(request => <article className="pair-request-card" key={request.requestId}><div><strong>{request.platformLabel}</strong><small>BLT {request.modVersion} · Requested {new Date(request.createdAt).toLocaleTimeString()}</small><code>Fingerprint {request.fingerprint}</code></div><div className="pair-decision" role="group" aria-label={`Decision for ${request.platformLabel}`}><button className={pairingDecisions[request.requestId] === "approved" ? "accept active" : "accept"} onClick={() => setPairingDecisions(current => ({ ...current, [request.requestId]: "approved" }))}><Check />Accept</button><button className={pairingDecisions[request.requestId] === "denied" ? "deny active" : "deny"} onClick={() => setPairingDecisions(current => ({ ...current, [request.requestId]: "denied" }))}><X />Deny</button></div>{pairingDecisions[request.requestId] ? <em>Decision staged — press Save to apply.</em> : <em>Waiting for your decision.</em>}</article>) : <p className="pairing-empty">No pending request. Generate a code, then press Pair in BLT Configure.</p>}<h2 className="installations-title">Connected installations</h2>{context.installations.length ? context.installations.map(item => <div className="installation-row" key={item.installationId}><span><strong>{item.revokedAt ? "Revoked" : "Connected mod"}</strong><small>Last seen {item.lastSeenAt ? new Date(item.lastSeenAt).toLocaleString() : "never"}</small></span>{!item.revokedAt ? <button onClick={() => void revoke(item.installationId)}><Unplug />Revoke</button> : null}</div>) : <p>No paired game installation yet.</p>}</div></section>
    <section className="command-config"><div className="command-config-head"><div><h2>Extension commands</h2><p>{enabledCount} of {manifest.actions.length} enabled · Select a command to edit the same handler settings exposed by BLT Configure.</p></div><label><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search commands" /></label></div><div className="config-categories">{categories.map(value => <button className={category === value ? "active" : ""} onClick={() => setCategory(value)} key={value}>{value}</button>)}</div><div className="command-toggle-list">{filtered.map(action => { const open = expandedAction === action.id; const preference = preferences.get(action.id); return <article className={open ? "command-config-item expanded" : "command-config-item"} key={action.id}><div className="command-config-summary"><label><input type="checkbox" checked={enabled.get(action.id) ?? action.enabledByDefault} onChange={event => setCommand(action, event.target.checked)} /><span className="sr-only">Enable !{action.legacyName}</span></label><button aria-expanded={open} onClick={() => setExpandedAction(open ? undefined : action.id)}><span><strong>!{action.legacyName}</strong><small>{action.description}</small></span><em>{action.mutatesCampaign ? "Changes campaign" : "Read-only"}</em><ChevronDown /></button></div>{open ? <div className="command-setting-panel"><div className="command-setting-title"><SlidersHorizontal /><span><strong>{action.handler}</strong><small>Handler configuration · Profile {draft.activeProfile}</small></span></div>{action.settings?.length ? <div className="command-setting-grid">{action.settings.map(setting => { const value = preference?.settings?.[setting.id] ?? setting.defaultValue; return <label key={setting.id}><span>{setting.label}</span>{setting.type === "boolean" ? <input type="checkbox" checked={Boolean(value)} onChange={event => setSetting(action, setting.id, event.target.checked)} /> : <input type={setting.type === "number" ? "number" : "text"} value={String(value)} onChange={event => setSetting(action, setting.id, setting.type === "number" ? Number(event.target.value) : event.target.value)} />}</label>})}</div> : <p>This handler has no additional configurable properties.</p>}</div> : null}</article>})}</div></section></> : <section className="live-summary"><strong>{enabledCount}</strong><span>of {manifest.actions.length} Extension commands enabled</span><p>Use the full Extension configuration page to change individual commands and manage pairing.</p></section>}
    {(error || message) ? <div className={error ? "config-message error" : "config-message"} role="status">{error ?? message}</div> : null}
    <footer className="config-savebar"><span>{Object.keys(pairingDecisions).length ? "Unsaved pairing decision" : dirty ? "Unsaved changes" : "All changes saved"}</span><button disabled={!dirty} onClick={() => { setDraft(context.configuration); setPairingDecisions({}); setMessage(undefined); }}>Discard</button><button className="primary" disabled={!dirty || saving} onClick={() => void save()}><Save />{saving ? "Saving…" : "Save"}</button></footer>
  </main>;
}
