import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export const supportedLocales = ["en", "de", "fr", "it", "ja", "ko", "pl", "pt-BR", "ru", "es", "tr", "zh-Hans", "zh-Hant"] as const;
export type Locale = typeof supportedLocales[number];
export type MessageValues = Record<string, string | number>;

const en = {
  "language.label": "Language", "common.back": "Back to command bar", "common.loading": "Loading", "common.refresh": "Refresh", "common.tryAgain": "Try again", "common.ready": "Ready", "common.offline": "Offline", "common.close": "Close",
  "app.connecting": "Connecting to Bannerlord Twitch…", "app.open": "Open Bannerlord Twitch", "app.collapse": "Collapse Bannerlord Twitch overlay",
  "identity.shared": "Identity shared", "identity.required": "Identity required", "identity.share": "Share Twitch identity",
  "gold.label": "Hero gold", "gold.offline": "Game offline", "gold.adopt": "Adopt a hero",
  "command.workspace": "Command workspace", "command.placeholder": "Type a command…", "command.line": "Command line", "command.help.open": "Open command help", "command.help.dialog": "Command help", "command.run": "Run command", "command.suggestions": "Command suggestions", "command.argument": "Argument", "command.hint": "Tab completes · Enter runs · type !help for every command", "command.help.title": "Command Help", "command.help.available": "{count} available commands", "command.help.search": "Search commands", "command.help.category": "Command",
  "shortcut.inventory": "Inventory", "shortcut.inventory.detail": "Custom items and equipped slots", "shortcut.retinue": "Retinue", "shortcut.retinue.detail": "Live troops and elite retinue",
  "error.action": "Action failed", "error.command": "Command failed", "error.inventory": "Your inventory could not be loaded.", "error.retinue": "Your retinue could not be loaded.",
  "feed.label": "Private command feed", "feed.title": "Command Feed", "feed.count": "{count} command", "feed.count.other": "{count} commands", "feed.waitingFirst": "Waiting for your first command", "feed.clear": "Clear feed", "feed.history": "Private viewer history", "feed.results": "Your Command Results", "feed.none.title": "No commands yet", "feed.none.detail": "Actions you send from the Extension will appear here with their success or failure response.", "feed.empty": "Your private command results will stay visible here.", "feed.waiting": "Waiting for Bannerlord…", "feed.pending": "Pending", "feed.succeeded": "Succeeded", "feed.failed": "Failed",
  "inventory.storage": "PERSONAL STORAGE", "inventory.title": "My inventory", "inventory.subtitle": "Your custom items, kept here", "inventory.summary": "{hero} · {count} of {limit} customs", "inventory.private.title": "Your inventory is private", "inventory.private.detail": "Share your Twitch identity so BLT can find your adopted hero. Only you can receive this inventory.", "inventory.unavailable": "Inventory unavailable", "inventory.checking": "Checking your saddlebags…", "inventory.open": "Open your inventory", "inventory.open.detail": "This list stays open until you close it—no chat command and no disappearing overlay message.", "inventory.load": "Load my inventory", "inventory.slots": "Equipped slots", "inventory.slot.choose": "Choose a slot for the selected item", "inventory.slot.drag": "Drag an item here or select it, then choose a slot", "inventory.emptySlot": "Empty slot", "inventory.accepts": "Accepts {type}", "inventory.customStorage": "Custom storage", "inventory.selected": "Item #{index} selected", "inventory.equipHint": "Click or drag an item to equip it", "inventory.search": "Search your items", "inventory.equipped": "Equipped", "inventory.stored": "Stored", "inventory.noMatches": "No custom items match that search.", "inventory.updated": "Updated {time} · This view is visible only to you.", "inventory.justNow": "just now",
  "retinue.private.title": "Your retinue is private", "retinue.private.detail": "Share your Twitch identity to see and manage the troops attached to your adopted hero.", "retinue.privateRoster": "Private live roster", "retinue.title": "My Retinue", "retinue.forces": "{hero}'s personal forces", "retinue.loading": "Loading your hero's personal forces…", "retinue.calling": "Calling the banners…", "retinue.battle": "Battle Retinue", "retinue.elite": "Elite Retinue", "retinue.troop": "{count} troop", "retinue.troop.other": "{count} troops", "retinue.recruit": "Recruit / upgrade troops", "retinue.quantity": "{title} recruit or upgrade quantity", "retinue.send": "Send order", "retinue.upgradeAll": "Upgrade all", "retinue.tier": "Tier {tier}", "retinue.dismiss": "Dismiss", "retinue.empty": "No troops recruited yet.", "retinue.dismissAll": "Dismiss entire {kind}retinue", "retinue.privateNote": "Only you can see this roster. It stays open while you browse and refreshes after each change.",
  "battle.live": "Live battle", "battle.yourHero": "Your hero", "battle.roster": "Battle roster", "battle.streamerSide": "Streamer side", "battle.opposingSide": "Opposing side", "battle.team": "Team {number}", "battle.notDeployed": "Your hero is not currently deployed", "battle.notDeployedHint": "Use Summon or Attack to enter the battle.", "battle.health": "{name} health {current} of {maximum}", "battle.power": "Power", "battle.powerRemaining": "{name} {percent} percent remaining", "battle.powerReady": "{name} ready", "battle.cooldown": "Cooldown", "battle.gold": "Gold", "battle.xp": "XP", "battle.commands": "Battle commands", "battle.unavailable": "{name} unavailable: {reason}", "battle.cooldownLabel": "{name} cooldown {seconds} seconds", "battle.chooseFormation": "Choose formation", "battle.formation": "Formation",
  "config.requesting": "Requesting…", "config.unavailable": "Unavailable", "config.title": "Connect Bannerlord Twitch", "config.detail": "Enter this short-lived pairing code in BLT Configure. The mod connects outbound to the managed service; no local web server or Extension secret is required.", "config.copy": "Copy pairing code", "config.expires": "Expires {time}", "config.shortLived": "Short-lived code", "config.new": "New code", "config.copied": "Pairing code copied", "config.channel": "Channel", "config.configuration": "Configuration", "config.managed": "Managed by Twitch Extension",
  "diagnostics.label": "Local integration diagnostics", "diagnostics.serviceOnline": "Service online", "diagnostics.serviceOffline": "Service offline", "diagnostics.gameConnected": "Game connected", "diagnostics.gameOffline": "Game offline", "diagnostics.channel": "Channel {id}", "diagnostics.state": "State {time}", "diagnostics.none": "none"
} as const;
export type MessageKey = keyof typeof en;
type Catalog = Partial<Record<MessageKey, string>>;

const catalogs: Record<Locale, Catalog> = {
  en,
  de: { "language.label": "Sprache", "common.loading": "Laden", "common.refresh": "Aktualisieren", "common.ready": "Bereit", "gold.label": "Heldengold", "gold.offline": "Spiel offline", "gold.adopt": "Adoptiere einen Helden", "command.placeholder": "Befehl eingeben…", "command.help.title": "Befehlshilfe", "shortcut.inventory": "Inventar", "shortcut.retinue": "Gefolge", "feed.title": "Befehlsverlauf", "inventory.title": "Mein Inventar", "retinue.title": "Mein Gefolge", "battle.yourHero": "Dein Held", "battle.roster": "Kampfteilnehmer" },
  fr: { "language.label": "Langue", "common.loading": "Chargement", "common.refresh": "Actualiser", "common.ready": "Prêt", "gold.label": "Or du héros", "gold.offline": "Jeu hors ligne", "gold.adopt": "Adoptez un héros", "command.placeholder": "Saisissez une commande…", "command.help.title": "Aide des commandes", "shortcut.inventory": "Inventaire", "shortcut.retinue": "Suite", "feed.title": "Fil des commandes", "inventory.title": "Mon inventaire", "retinue.title": "Ma suite", "battle.yourHero": "Votre héros", "battle.roster": "Combattants" },
  it: { "language.label": "Lingua", "common.loading": "Caricamento", "common.refresh": "Aggiorna", "common.ready": "Pronto", "gold.label": "Oro dell'eroe", "command.placeholder": "Digita un comando…", "command.help.title": "Guida ai comandi", "shortcut.inventory": "Inventario", "shortcut.retinue": "Seguito", "feed.title": "Cronologia comandi", "inventory.title": "Il mio inventario", "retinue.title": "Il mio seguito", "battle.yourHero": "Il tuo eroe", "battle.roster": "Combattenti" },
  ja: { "language.label": "言語", "common.loading": "読み込み中", "common.refresh": "更新", "common.ready": "準備完了", "gold.label": "英雄のゴールド", "command.placeholder": "コマンドを入力…", "command.help.title": "コマンドヘルプ", "shortcut.inventory": "インベントリ", "shortcut.retinue": "従者隊", "feed.title": "コマンド履歴", "inventory.title": "マイインベントリ", "retinue.title": "マイ従者隊", "battle.yourHero": "あなたの英雄", "battle.roster": "戦闘参加者" },
  ko: { "language.label": "언어", "common.loading": "불러오는 중", "common.refresh": "새로고침", "common.ready": "준비됨", "gold.label": "영웅 골드", "command.placeholder": "명령어 입력…", "command.help.title": "명령어 도움말", "shortcut.inventory": "인벤토리", "shortcut.retinue": "수행단", "feed.title": "명령 기록", "inventory.title": "내 인벤토리", "retinue.title": "내 수행단", "battle.yourHero": "내 영웅", "battle.roster": "전투 참가자" },
  pl: { "language.label": "Język", "common.loading": "Ładowanie", "common.refresh": "Odśwież", "common.ready": "Gotowe", "gold.label": "Złoto bohatera", "command.placeholder": "Wpisz komendę…", "command.help.title": "Pomoc komend", "shortcut.inventory": "Ekwipunek", "shortcut.retinue": "Świta", "feed.title": "Historia komend", "inventory.title": "Mój ekwipunek", "retinue.title": "Moja świta", "battle.yourHero": "Twój bohater", "battle.roster": "Uczestnicy bitwy" },
  "pt-BR": { "language.label": "Idioma", "common.loading": "Carregando", "common.refresh": "Atualizar", "common.ready": "Pronto", "gold.label": "Ouro do herói", "command.placeholder": "Digite um comando…", "command.help.title": "Ajuda de comandos", "shortcut.inventory": "Inventário", "shortcut.retinue": "Séquito", "feed.title": "Histórico de comandos", "inventory.title": "Meu inventário", "retinue.title": "Meu séquito", "battle.yourHero": "Seu herói", "battle.roster": "Combatentes" },
  ru: { "language.label": "Язык", "common.loading": "Загрузка", "common.refresh": "Обновить", "common.ready": "Готово", "gold.label": "Золото героя", "command.placeholder": "Введите команду…", "command.help.title": "Справка по командам", "shortcut.inventory": "Инвентарь", "shortcut.retinue": "Свита", "feed.title": "История команд", "inventory.title": "Мой инвентарь", "retinue.title": "Моя свита", "battle.yourHero": "Ваш герой", "battle.roster": "Участники боя" },
  es: { "language.label": "Idioma", "common.loading": "Cargando", "common.refresh": "Actualizar", "common.ready": "Listo", "gold.label": "Oro del héroe", "command.placeholder": "Escribe un comando…", "command.help.title": "Ayuda de comandos", "shortcut.inventory": "Inventario", "shortcut.retinue": "Séquito", "feed.title": "Historial de comandos", "inventory.title": "Mi inventario", "retinue.title": "Mi séquito", "battle.yourHero": "Tu héroe", "battle.roster": "Combatientes" },
  tr: { "language.label": "Dil", "common.loading": "Yükleniyor", "common.refresh": "Yenile", "common.ready": "Hazır", "gold.label": "Kahraman altını", "command.placeholder": "Komut yaz…", "command.help.title": "Komut yardımı", "shortcut.inventory": "Envanter", "shortcut.retinue": "Müfreze", "feed.title": "Komut geçmişi", "inventory.title": "Envanterim", "retinue.title": "Müfrezem", "battle.yourHero": "Kahramanın", "battle.roster": "Savaşçılar" },
  "zh-Hans": { "language.label": "语言", "common.loading": "加载中", "common.refresh": "刷新", "common.ready": "就绪", "gold.label": "英雄金币", "command.placeholder": "输入命令…", "command.help.title": "命令帮助", "shortcut.inventory": "物品栏", "shortcut.retinue": "亲卫队", "feed.title": "命令记录", "inventory.title": "我的物品栏", "retinue.title": "我的亲卫队", "battle.yourHero": "你的英雄", "battle.roster": "参战者" },
  "zh-Hant": { "language.label": "語言", "common.loading": "載入中", "common.refresh": "重新整理", "common.ready": "就緒", "gold.label": "英雄金幣", "command.placeholder": "輸入指令…", "command.help.title": "指令說明", "shortcut.inventory": "物品欄", "shortcut.retinue": "親衛隊", "feed.title": "指令記錄", "inventory.title": "我的物品欄", "retinue.title": "我的親衛隊", "battle.yourHero": "你的英雄", "battle.roster": "參戰者" }
};

const labels: Record<Locale, string> = { en: "English", de: "Deutsch", fr: "Français", it: "Italiano", ja: "日本語", ko: "한국어", pl: "Polski", "pt-BR": "Português (Brasil)", ru: "Русский", es: "Español", tr: "Türkçe", "zh-Hans": "简体中文", "zh-Hant": "繁體中文" };
const storageKey = "blt.extension.locale.v1";
export function normalizeLocale(value?: string | null): Locale { const normalized = (value ?? "").replace("_", "-").toLowerCase(); if (normalized.startsWith("zh-hant") || normalized === "zh-tw" || normalized === "zh-hk") return "zh-Hant"; if (normalized.startsWith("zh")) return "zh-Hans"; if (normalized.startsWith("pt")) return "pt-BR"; return supportedLocales.find(locale => locale.toLowerCase() === normalized || locale.split("-")[0] === normalized.split("-")[0]) ?? "en"; }
function twitchLocale() { const query = new URLSearchParams(window.location.search); return query.get("locale") ?? query.get("language") ?? navigator.language; }
function interpolate(message: string, values?: MessageValues) { return message.replace(/\{(\w+)\}/g, (_, key: string) => String(values?.[key] ?? `{${key}}`)); }
interface I18nValue { locale: Locale; setLocale(locale: Locale): void; t(key: MessageKey, values?: MessageValues): string; number(value: number): string; time(value: string | Date): string; localeOptions: Array<{ value: Locale; label: string }> }
const defaultI18n: I18nValue = { locale: "en", setLocale: () => undefined, t: (key, values) => interpolate(en[key], values), number: value => value.toLocaleString(), time: input => new Date(input).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }), localeOptions: supportedLocales.map(value => ({ value, label: labels[value] })) };
const I18nContext = createContext<I18nValue>(defaultI18n);
export function I18nProvider({ children }: { children: ReactNode }) { const [locale, setLocaleState] = useState<Locale>(() => normalizeLocale(localStorage.getItem(storageKey) ?? twitchLocale())); useEffect(() => { document.documentElement.lang = locale; }, [locale]); const setLocale = useCallback((next: Locale) => { localStorage.setItem(storageKey, next); setLocaleState(next); }, []); const value = useMemo<I18nValue>(() => ({ locale, setLocale, t: (key, values) => interpolate(catalogs[locale][key] ?? en[key], values), number: number => new Intl.NumberFormat(locale).format(number), time: input => new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(input)), localeOptions: supportedLocales.map(value => ({ value, label: labels[value] })) }), [locale, setLocale]); return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>; }
export function useI18n() { return useContext(I18nContext); }
export function LanguageSelector() { const { locale, setLocale, localeOptions, t } = useI18n(); return <label className="language-selector"><span>{t("language.label")}</span><select aria-label={t("language.label")} value={locale} onChange={event => setLocale(event.target.value as Locale)}>{localeOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
